name: Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake zip libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libwayland-egl-backend-dev libxkbcommon-dev libegl1-mesa-dev
      
      - name: Setup repo
        run: |
          ./setup.sh

      - name: Configure CMake with Ninja
        run: |
          mkdir -p build
          cd build
          cmake -G Ninja ..

      - name: Build with Ninja
        run: |
          cd build
          ninja

      - name: Create zip artifact
        run: |
          cd build
          zip -r artifact.zip RadiumRuntime Editor libRadium.a subprojects/Rune/libRune.a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: radium-linux-x86_64
          path: build/artifact.zip
  emscripten:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y ninja-build cmake zip libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libwayland-egl-backend-dev libxkbcommon-dev libegl1-mesa-dev
      
      - name: Setup repo
        run: |
          ./setup.sh

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          # Make sure to set a version number!
          version: 4.0.15
          # This is the name of the cache folder.
          # The cache folder will be placed in the build directory,
          #  so make sure it doesn't conflict with anything!
          actions-cache-folder: 'emsdk-cache'

      - name: Verify
        run: emcc -v

      - name: Configure CMake with Ninja
        run: |
          mkdir -p build
          cd build
          emcmake cmake -G Ninja ..

      - name: Build with Ninja
        run: |
          cd build
          ninja

      - name: Create zip artifact
        run: |
          cd build
          zip -r artifact.zip RadiumRuntime.html RadiumRuntime.js RadiumRuntime.data RadiumRuntime.wasm libRadium.a

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: radium-emscripten32
          path: build/artifact.zip
  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSYS2 (for patch)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: patch
        
      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup repository (clone + patch)
        shell: cmd
        run: |
          cd subprojects
          call clone.bat
          call patch.bat
          cd Rune\subprojects
          call clone.bat

      - name: Configure CMake (Release)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../msvc.toolchain.cmake

      - name: Build
        run: cmake --build build --config Release --verbose

      - name: Create zip artifact
        run: |
          cd build
          powershell Compress-Archive -Path RadiumRuntime.exe,Editor.exe,Radium.lib,bin\Rune.lib -DestinationPath artifact.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: radium-windows-x86_64
          path: build/artifact.zip
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build cmake zip \
            libx11-dev libxext-dev libxrandr-dev libxinerama-dev \
            libxcursor-dev libxi-dev libwayland-dev \
            libwayland-egl-backend-dev libxkbcommon-dev libegl1-mesa-dev

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK 29.0.14033849
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r29

      - name: Setup repo
        run: ./setup.sh

      - name: Build Android APK
        working-directory: android
        run: ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: radium-android-x86_64
          path: android/distribution/android/app/outputs/apk/debug/app-debug.apk
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz cmake ninja-build

      - name: Setup repo
        run: ./setup.sh

      - name: Configure CMake
        run: cmake -B build -G Ninja

      - name: Build docs
        run: cmake --build build --target doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html