name: Build (windows)

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
    
env:
  CC: cl
  CXX: cl
  CMAKE_GENERATOR: "Ninja"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install MSYS2 (for patch)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: patch
        
      - name: Configure MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup repository (clone + patch)
        shell: cmd
        run: |
          cd subprojects
          call clone.bat
          call patch.bat
          cd Rune\subprojects
          call clone.bat

      - name: Configure CMake (Release)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../msvc.toolchain.cmake

      - name: Build
        run: cmake --build build --config Release --verbose

      - name: Create zip artifact
        run: |
          cd build
          powershell Compress-Archive -Path RadiumRuntime.exe,Editor.exe,libRadium.lib,subprojects\Rune\libRune.lib -DestinationPath artifact.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifact
          path: build/artifact.zip
